PROJECT_Trading_Platform/Front-5/Controllers/AkauntController.cs
//using front_2.Models;
using Front_5.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Front_5.Models.Extensions;
using Front_5.Extensions;
using Front_5.Services;
using Microsoft.AspNetCore.Authorization;
using front_5.Models;
using System.Security.Cryptography.X509Certificates;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.CodeAnalysis.Elfie.Serialization;
using static System.Net.WebRequestMethods;
using Stripe;
using System.Numerics;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Threading.Tasks;
using System;
using Stripe.FinancialConnections;
using System.Reflection.Metadata;

//using front_5.Models;


namespace Front_5.Controllers
{
    public class AkauntController : Controller
    {
        private readonly Appdbcontext appdbcontext;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IEmailService _emailservice;
        public AkauntController(Appdbcontext _appdbcontext,UserManager<User> userManager, SignInManager<User> signInManager,IEmailService emailservice, RoleManager<IdentityRole> roleManager)
        {
            appdbcontext = _appdbcontext;
            _userManager = userManager;
            _signInManager = signInManager;
            _emailservice = emailservice;
            _roleManager = roleManager;
        }

        [HttpGet]
        public IActionResult AccessDenied()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterVM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
      
            User Users = new User
            {
                Name = model.Name,  
                Surname = model.Surname,
                Age = model.Age,
                Email = model.Email,
                UserName = model.Name
            };
            var result = await _userManager.CreateAsync(Users, model.Password);
            if (result.Succeeded)
            {

              var token = await _userManager.GenerateEmailConfirmationTokenAsync(Users);
               var confirmationLink = Url.Action("ConfirmEmail", "Account", new { userId = Users.Id, token = token }, Request.Scheme);
                // await _emailservice.SendEmailAsync(model.Email,"Confirm please", subject);

                var subject = $@"
<!DOCTYPE html>
<html lang=""en"">
<head>
    <meta charset=""UTF-8"">
    <meta http-equiv=""X-UA-Compatible"" content=""IE=edge"">
    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">
    <title>Email Confirmation</title>
</head>
<body style=""font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px;"">
    <div style=""max-width: 600px; margin: 0 auto; background-color: #ffffff; padding: 30px; border-radius: 10px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);"">
        <h2 style=""color: #333333;"">Confirm Your Email Address</h2>
        <p style=""color: #666666;"">Hello,</p>
        <p style=""color: #666666;"">Thank you for signing up. Please confirm your email address by clicking the button below:</p>
        <a href=""{confirmationLink}"" style=""display: inline-block; background-color: #4CAF50; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; margin-top: 20px;"">Confirm Email</a>
        <p style=""color: #666666; margin-top: 20px;"">If you did not create an account, no further action is required.</p>
        <p style=""color: #666666;"">Regards,<br>Your Name</p>
    </div>
</body>
</html>";

                await _emailservice.SendEmailAsync(model.Email, "Confirm your email", subject);
                //await _signInManager.SignInAsync(Users, true);
                await _userManager.AddToRoleAsync(Users,"User");
                return RedirectToAction("Index", "Home");

            }
            foreach (var item in result.Errors)
            {
                ModelState.AddModelError("", item.Description);
            }

            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginVM model)
        {
            //if (!ModelState.IsValid)
            //{
            //    ModelState.AddModelError("", "Something incorrent");
            //}
            var user = await _userManager.FindByEmailAsync(model.Email);
           
            if (user != null)
            {
                var result = await _signInManager.PasswordSignInAsync(user, model.Password, model.Isremember, false);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", "Password or email incorrent");
                }
            }
            _signInManager.SignInAsync(user, isPersistent: true);
            //_emailService.SendEmailAsync()
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        public async Task SeedRoles()
        {
            if (!await _roleManager.RoleExistsAsync(roleName: "Admin"))
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName: "Admin"));
            }
            if (!await _roleManager.RoleExistsAsync(roleName: "User"))
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName: "User"));
            }
        }
        public async Task SeedAdmin()
        {
            if (await _userManager.FindByEmailAsync("kermiv@gmail.com") == null)
            {
                //User admin = new User
                //{
                //    Email = "kermiv@gmail.com",
                //    UserName = "kermiv@gmail.com"
                //};
                User admin = new User
                {
                    Name = "Admin",
                    Surname = "Admin",
                    Age = 100,
                    Email = "kermiv@gmail.com",
                    UserName = "kermiv@gmail.com"
                };

                IdentityResult result = await _userManager.CreateAsync(admin, "123456AGK");

                if (result.Succeeded)
                {
                    await _userManager.AddToRoleAsync(admin, "Admin");
                    await _signInManager.SignInAsync(admin, isPersistent: true);

                   RedirectToAction("Index", "Home");
                }
               
            }
           
        }

   
    }
}

PROJECT_Trading_Platform/Front-5/Views/Akaunt/AccessDenied.cshtml
@{
    Layout = null;
}
<h1>404</h1>
<p>ACCESS DENIED</p>

<style>
    body {
        background-image: url('/assets/img/logo/denied.gif');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 800px 650px;
        background-position: center;
        background-color: black;
        font-family: "Lucida Console", "Courier New", monospace;
    }

    h1 {
        color: white;
        font-size: 135px;
        text-align: center;
    }

    p {
        color: red;
        font-size: 90px;
        text-align: center;
    }
</style>

PROJECT_Trading_Platform/Front-5/Views/Akaunt/Login.cshtml
@model LoginVM
<div class="search_area">
    <div class="search_close">
        <span><i class="fal fa-times"></i></span>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12">
                <div class="search-wrapper text-center">
                    <h2>search</h2>
                    <div class="search-filtering pt-30">
                        <div class="search_tab">
                            <ul class="nav nav-tabs justify-content-center mb-55" id="myTab2" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="select11" data-bs-toggle="tab"
                                            data-bs-target="#select1" type="button" role="tab"
                                            aria-selected="true">
                                        All categories
                                    </button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="select22" data-bs-toggle="tab"
                                            data-bs-target="#select2" type="button" role="tab"
                                            aria-selected="false">
                                        Basketball
                                    </button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" data-bs-toggle="tab"
                                            data-bs-target="#select3" type="button" role="tab"
                                            aria-selected="false" id="select33">
                                        Handbag
                                    </button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="select44" data-bs-toggle="tab"
                                            data-bs-target="#select4" type="button" role="tab"
                                            aria-selected="false">
                                        Sportswear
                                    </button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="select55" data-bs-toggle="tab"
                                            data-bs-target="#contact3" type="button" role="tab"
                                            aria-selected="false">
                                        Youth
                                    </button>
                                </li>
                            </ul>
                            <div class="tab-content" id="myTabContent2">
                                <div class="tab-pane fade show active" id="select1" role="tabpanel">
                                </div>
                                <div class="tab-pane fade" id="select2" role="tabpanel">
                                </div>
                                <div class="tab-pane fade" id="select3" role="tabpanel">
                                </div>
                                <div class="tab-pane fade" id="select4" role="tabpanel">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="main_search">
                        <form action="#">
                            <input type="text" name="search" placeholder="search products">
                            <button class="m-search"><i class="fal fa-search d-sm-none d-md-block"></i></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- breadcrumb area start -->
<div class="page-layout about" data-background="/assets/img/slider/shop.jpg">
    <div class="container">
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                <div class="breadcrumb-area text-center">
                    <h2 class="page-title">My account</h2>
                    <div class="breadcrumb-menu">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb justify-content-center">
                                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                                <li class="breadcrumb-item"><a href="login.html">My account</a></li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- breadcrumb area end -->

<div class="login_register_area" id="Loggino">
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-xl-5 col-lg-6 col-md-12 col-sm-12 offset-xl-1">
                <h3 class="title-7">Login</h3>
                <div class="login_wrapper">
                    <form asp-controller="Akaunt" asp-action="Login" method="post">
                        <div class="input_wrap">
                            <label>Email<span>*</span></label>
                            <input type="text" name="Email">
                            <span style="color:red" asp-validation-for="Email"></span>
                        </div>
                        <div class="input_wrap">
                            <label>Password<span>*</span></label>
                            <input type="pass" name="Password">
                            <span style="color:red" asp-validation-for="Password"></span>
                            <span class="show-pass"><i class="far fa-eye-slash"></i></span>
                        </div>
                        <div class="input_wrapp-2">
                            <input type="checkbox" name="Isremember">
                            <span>Remember me </span>
                        </div>
                        <div class="input_wrap">
                            <button type="submit">log in</button>
                        </div>
                       
                    </form>
                    <div class="input_wrap">
                        <a asp-controller="Akaunt" asp-action="Register">Or register</a>
                    </div>
                </div>
            </div>
           
        </div>
    </div>
</div>

PROJECT_Trading_Platform/Front-5/Views/Akaunt/Register.cshtml
@model RegisterVM

<h1 style="margin:20px;">Register</h1>
<div class="container">
    <div class="row justify-content-center align-items-center">
<div class="col-xl-5 col-lg-6 col-md-12 col-sm-12 text-center ">
    <h3 class="title-7">register</h3>
    <div class="login_wrapper login_wrapper_2">
        @Html.ValidationSummary(true,"",new {@class="text-danger"})
        <form asp-controller="Akaunt" asp-action="Register" method="post">
                    <div class="input_wrap">
                        <label>User Name<span>*</span></label>
                        <input asp-for="Name" type="text">
                        <span style="color:red" asp-validation-for="Name"></span>
                    </div>
                    <div class="input_wrap">
                        <label>User Surname<span>*</span></label>
                        <input asp-for="Surname" type="text">
                        <span style="color:red" asp-validation-for="Surname"></span>
                    </div>
                    <div class="input_wrap">
                        <label>User Age<span>*</span></label>
                        <input asp-for="Age" type="text">
                        <span style="color:red" asp-validation-for="Age"></span>
                    </div>

            <div class="input_wrap">
                <label>Email address<span>*</span></label>
                <input asp-for="Email" type="email">
                <span style="color:red" asp-validation-for="Email"></span>
            </div>
            <div class="input_wrap">
                <label>Password<span>*</span></label>
                <input asp-for="Password" type="text">
                <span style="color:red" asp-validation-for="Password"></span>
            </div>
            <div class="input_wrap">
                <label>Confirm password<span>*</span></label>
                <input asp-for="confirmpass" type="text">
                <span style="color:red" asp-validation-for="confirmpass"></span>
            </div>
            <div class="input_wraph">
                <label>Remember me!<span>*</span></label>
                 <input asp-for="Isremember" type="checkbox">
                 <span style="color:red" asp-validation-for="Isremember"></span>
            </div>
            <div class="input_wrap input_wrap_3">
                <span class="mb-10 pt-15">A password will be sent to your email address.</span>
                <p class="mb-30">Your personal data will be used to support your experience throughout this website, to manage access to your account, and for other purposes described in our privacy policy.</p>
                <button type="submit">register</button>
            </div>
        </form>
    </div>
</div>
    </div>
</div>