PROJECT_Trading_Platform/Front-5/Areas/Admin/Controllers/DashController.cs
//using front_2.Models;
using Front_5.Controllers;
using Front_5.Models;
using Microsoft.AspNetCore.Mvc;
using Front_5.Extensions;
using System;
using NuGet.ContentModel;
using System.Reflection.Metadata;
using Microsoft.EntityFrameworkCore;
using front_5.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using X.PagedList;
using Microsoft.CodeAnalysis;
namespace Front_5.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class DashController : Controller
    {
        private readonly Appdbcontext appdbcontext;
        private readonly IWebHostEnvironment _env;
        private readonly ILogger<DashController> _logger;
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private bool sert = false;
        // private readonly Appdbcontext _context;
        public DashController(Appdbcontext _appdbcontext , ILogger<DashController> logger, IWebHostEnvironment env, UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
        {
            appdbcontext = _appdbcontext;
            _env = env;
            _logger = logger;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public IActionResult Index(int? i)
        {
            var pageNumber = i ?? 1;
            var pageSize = 5;
            var cards = appdbcontext.Cards.ToList();
            appdbcontext.Cards.Include(sp => sp.Color).ToList();
            var model = new Twomodel
            {

                Card = appdbcontext.Cards.ToList(),
                Stat = appdbcontext.States.ToList(),
                Slider_L = appdbcontext.Sliders.ToList(),
                Slider_T = appdbcontext.Sliders.FirstOrDefault(),
                Card_t = appdbcontext.Cards.FirstOrDefault(),
                Stat_t = appdbcontext.States.FirstOrDefault(),
                PagedCards = cards.ToPagedList(pageNumber, pageSize)
            };

            return View(model);
           
        }

        public IActionResult Add()
        {
            ViewBag.imagem = appdbcontext.Images.ToList();
            ViewBag.Categories = appdbcontext.Category.ToList();
            ViewBag.Colors = appdbcontext.Colors.ToList();
            ViewBag.Categories_two = appdbcontext.Category_two.ToList();
            ViewBag.Size= appdbcontext.Size.ToList();

            return View();
		}

        public IActionResult Delete(int id)
        {
            var s = appdbcontext.Cards.Find(id);
            if (s != null)
            {
                appdbcontext.Cards.Remove(s);
                appdbcontext.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Add(Sport_pro card, IFormFile file1, IFormFile file2, List<IFormFile> Images)
        {
            if (!ModelState.IsValid)
            {

                return RedirectToAction("Add");
            }
            // Validate required files
            if (file1 == null || file2 == null || Images == null || !Images.Any())
            {
                ModelState.AddModelError("Add", "Both photos and at least one additional image are required");
                return View("Index");
            }

            // Save the first photo
            string filename1 = await file1.SaveFileAsync(_env.WebRootPath, "assets/img/product");

            // Save the second photo
            string filename2 = await file2.SaveFileAsync(_env.WebRootPath, "assets/img/product");

            // Assign the filenames to the card properties
            card.photo1 = filename1;
            card.photo2 = filename2;

            // Initialize the Images collection if not already done
            card.Images = new List<Images>();

            // Save each additional image and create an Images entity for each
            foreach (var imageFile in Images)
            {
                string imageFilename = await imageFile.SaveFileAsync(_env.WebRootPath, "assets/img/product");
                card.Images.Add(new Images
                {
                    ImaUrl = $"{imageFilename}",
                    CardId = card.Id
                });
            }

            // Add the card to the context and save changes
            appdbcontext.Cards.Add(card);
            await appdbcontext.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Categories = appdbcontext.Category.ToList();
            ViewBag.Categories_two = appdbcontext.Category_two.ToList();
            ViewBag.Colors= appdbcontext.Colors.ToList();
            ViewBag.Size = appdbcontext.Size.ToList();
            ViewBag.Images = appdbcontext.Images.ToList();
            if (id == 0)
            {
                return NotFound();
            }
            var model = appdbcontext.Cards.FirstOrDefault(s => s.Id == id);
            if (model == null)
            {
                return RedirectToAction("Index");
            }
            
            return View(model);
        }

        [HttpPost]

        public async Task<IActionResult> Edit(Sport_pro card,IFormFile file1, IFormFile file2, List<IFormFile> Images)
        {
            //    if (!ModelState.IsValid)
            //    {
            //        return View(card);
            //    }
            if (file1 == null || file2 == null || Images == null || !Images.Any())
            {
                ModelState.AddModelError("Add", "Both photos and at least one additional image are required");
                return View("Index");
            }

            // Save the first photo
            string filename1 = await file1.SaveFileAsync(_env.WebRootPath, "assets/img/product");

            // Save the second photo
            string filename2 = await file2.SaveFileAsync(_env.WebRootPath, "assets/img/product");

            // Assign the filenames to the card properties
            card.photo1 = filename1;
            card.photo2 = filename2;
            card.Images = new List<Images>();
            foreach (var imageFile in Images)
            {
                string imageFilename = await imageFile.SaveFileAsync(_env.WebRootPath, "assets/img/product");
                card.Images.Add(new Images
                {
                    ImaUrl = $"{imageFilename}",
                    CardId = card.Id
                });
            }
            appdbcontext.Cards.Update(card);
            appdbcontext.SaveChanges();
            return RedirectToAction("Index");
        }


		[HttpPost]
		public async Task<IActionResult> Addtocategory(Category category)
		{

			//if (!ModelState.IsValid)
			//{
			//	return RedirectToAction("Add");
			//}
			appdbcontext.Category.Add(category);
			appdbcontext.SaveChanges();
			return RedirectToAction("Categor");
		}

        public IActionResult Ablog()
        {
            var model = new Twomodel
            {

                Card = appdbcontext.Cards.ToList(),
                Stat = appdbcontext.States.ToList(),
                Card_t = appdbcontext.Cards.FirstOrDefault(),
                Stat_t = appdbcontext.States.FirstOrDefault()
            };
            return View(model);
        }

        public IActionResult delete_blog(int id)
        {
            var s = appdbcontext.States.Find(id);
            if (s != null)
            {
                appdbcontext.States.Remove(s);
                appdbcontext.SaveChanges();
            }
            return RedirectToAction("Ablog");
        }

        public async Task<IActionResult>addtoblog(state card, IFormFile file3)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            if (file3 == null)
            {
                ModelState.AddModelError("Add", "Both photos are required");
                return View("Index");
            }
            string filename1 = await file3.SaveFileAsync(_env.WebRootPath, "assets/img/blog");

            // Assign the filenames to the card properties
            card.sekil = filename1;

            appdbcontext.States.Add(card);
            appdbcontext.SaveChanges();
            return RedirectToAction("Add");
        
        }


        public IActionResult Categor(int id)
        {       
			ViewBag.Categories = appdbcontext.Category.ToList();
            return View();     
		}

        [HttpGet]
        public IActionResult Edit_category(int id)
        {
            ViewBag.Categories = appdbcontext.Category.ToList();
            if (id == 0)
            {
                return NotFound();
            }
            var model = appdbcontext.Category.FirstOrDefault(s => s.Id == id);
            if (model == null)
            {
                return RedirectToAction("Index");
            }

            return View(model);
        }
   
        public IActionResult Edit_cat(int id)
        {  
            return Json(id);
        }

        public IActionResult Edit_category5(int id,string name, bool ischeck)
        {         
            var category = appdbcontext.Category.Find(id);
            if (category == null)
            {
                return NotFound();
            }        
            category.Name = name;
            category.ischeck =ischeck;
            appdbcontext.Category.Update(category);
            appdbcontext.SaveChanges();
            return RedirectToAction("Categor", "dash", new { area = "admin" });
        }


        [HttpPost]
        public IActionResult UpdateCategory([FromBody] UpdateCategoryRequest request)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var category = appdbcontext.Category.Find(request.Id);
            if (category == null)
            {
                return NotFound();

PROJECT_Trading_Platform/Front-5/Areas/Admin/Views/Dash/Ablog.cshtml
@* @model state; *@
@model Front_5.Models.Twomodel;
<h2 style="margin-left:20px;">Add new blog</h2>
<style>
    .custom-border {
        border: 3px solid #ccc; /* Example border style */
        border-radius: 5px; /* Optional: Adds rounded corners */
       
    }
</style>
<div class="mb-2 m-5">
    <form method="post" asp-area="admin" asp-controller="Dash" asp-action="addtoblog" enctype="multipart/form-data">
        <label for="ad" class="form-label">Text Input:</label>
        <input type="text" class="form-control form-control-lg border border-success" id="ad" name="ad" placeholder="Enter name" />

        <label for="sekil" class="form-label mt-3">Select Image:</label>
        <input type="file" class="form-control form-control-lg border border-success input-lg" id="sekil" name="file3" />

        <label for="stat" class="form-label mt-3">Textarea:</label>
        <textarea class="form-control form-control-lg border border-success input-lg" id="stat" name="stat" rows="3" placeholder="Add blog"></textarea>

        <button type="submit" class="btn btn-primary mt-3">Add</button>
    </form>


    <ul>
        @foreach (var state in Model.Stat) @* asp-action = "delete_blog asp-route-id="@state.Id"" *@
        {
            <li><h5>@state.ad<a href="#" onclick="confirmDelete(@state.Id)">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Delete this blog</a></h5></li>
        }
    </ul>
</div>
<script>
    function confirmDelete(itemId) {
        Swal.fire({
            title: 'Bu bloqu silmek istediyirsiniz ?',
            text: 'Silindikden sonra geri qaytara bilmeyeceksiz!',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Beli, sil!',
            cancelButtonText: 'Xeyr, emin deyilem!',
            reverseButtons: true
        }).then((result) => {
            if (result.isConfirmed) {
                // If user confirms, redirect to the delete action URL
                window.location.href = '/Admin/Dash/delete_blog/' + itemId;
            } else {
                // If user cancels, do nothing
            }
        });
    }
</script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

PROJECT_Trading_Platform/Front-5/Areas/Admin/Views/Dash/Add.cshtml
@* @model Category; *@
@model Sport_pro;

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

@* <form  method="post" asp-area="admin" asp-controller="slider" asp-action="Add" enctype="multipart/form-data">
    <label>Text:</label>
    <input type="text" id="TExt" asp-for="text2"><br><br>

    <label>Picture:</label>
   @*  <input type="file" id="file" name="file" multiple asp-for="picture"><br><br> 

    <input type="file" id="Sekil" asp-for="file"><br><br>

    <input type="submit">
</form>  *@
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Add new product
</button>
<button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal2">
    Add new category
</button>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add new product</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <form method="post" asp-area="admin" asp-controller="dash" asp-action="Add" enctype="multipart/form-data">
                    <label>Text:</label>
                    <input class="form-control form-control-sm" type="text" id="Text" asp-for="name">

                    <label>Picture 1</label>
                    <input class="form-control form-control-sm" type="file" id="photo1" asp-for="file1">
                    <span style="color:red" asp-validation-for="file1"></span>
                    <label>Picture 2</label>
                    <input class="form-control form-control-sm" type="file" id="photo2" asp-for="file2" multiple>
                    <span style="color:red" asp-validation-for="file2"></span>
                    <label>Other pictures</label>
                    <input class="form-control form-control-sm" type="file" id="photo2" asp-for="Images" multiple="multiple">
                    <span style="color:red" asp-validation-for="Images"></span>
                    <label>Price</label>
                    <input class="form-control form-control-sm" type="text" id="price" asp-for="price"><br>

                    <label>Description</label>
                    <textarea class="form-control form-control-sm" asp-for="description" id="description" name="description" rows="4" cols="50"></textarea><br>
                    <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" asp-for="CategoryId">
                        @foreach(var item in ViewBag.Categories)
                        {
                        <option value="@item.Id">@item.Name</option>
                            
                        }
                    </select>
                    <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" asp-for="CategorytwoId">
                        @foreach (var item in ViewBag.Categories_two)
                        {
                            <option value="@item.Id">@item.Name</option>

                        }
                    </select>
                    
                    <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" asp-for="ColorId">
                        @foreach (var item in ViewBag.Colors)
                        {
                            <option value="@item.Id">@item.color</option>
                        }
                    </select>
                    <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" asp-for="SizeId">
                        @foreach (var item in ViewBag.Size)
                        {
                            <option value="@item.Id">@item.name</option>
                        }
                    </select>
                    <br><br>
                    <button type="submit" class="btn btn-primary">Add new product</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </form>
            </div>

        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add new category</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" asp-area="admin" asp-controller="dash" asp-action="Addtocategory" enctype="multipart/form-data">
                    <label>Add category name:</label>
                    

                    <input class="form-control form-control-sm" type="text" id="category" asp-for="Category.Name"><br>
                    <input type="checkbox" style="width:20px;height:20px;" asp-for="Category.ischeck" value="true" /><br /><br />
                    <button type="submit" class="btn btn-primary">Add</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </form>
            </div>

        </div>
    </div>
</div>

PROJECT_Trading_Platform/Front-5/Areas/Admin/Views/Dash/Categor.cshtml
@model Category
<h1>Category</h1>
<style>
    table, th, td {
        border: 1px solid black;
        padding:20px;
    }
</style>
@* <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal2">
    Add new category
</button> *@
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Id</th>
            <th>IsCheck</th>
            <th>Edit</th>
        </tr>
@* <button onclick="fetchDataFromServer()">Fetch Data</button> *@
     
@foreach (var item in ViewBag.Categories)
{
@* <tr>
     <td><a asp-area="admin" asp-controller="dash"  asp-route-id="@item.Id">@item.Name</a></td>
     <td>@item.Id</td>
     <td><input type="checkbox" asp-action="UpdateCategory(3)" class="category-checkbox" data-id="@item.Id" @(item.ischeck ? "checked" : "")></td>
     <td><a asp-route-id="@item.Id" class="edit-link" onclick="ajaxx(@item.Id,`@item.Name`)" asp-action="Edit_cat" data-bs-toggle="modal" data-bs-target="#exampleModal3">Edit</a></td>
</tr>  *@
            <tr>
                <td><a asp-area="admin" asp-controller="dash" asp-route-id="@item.Id">@item.Name</a></td>
                <td>@item.Id</td>
                <td>
                    <input type="checkbox" class="category-checkbox" data-id="@item.Id" @(item.ischeck ? "checked" : "") onchange="updateCategory(@item.Id, this.checked)">
                </td>
                <td>
                    <a asp-route-id="@item.Id" class="edit-link" onclick="ajaxx(@item.Id, `@item.Name`)" asp-action="Edit_cat" data-bs-toggle="modal" data-bs-target="#exampleModal3">Edit</a>
                </td>
            </tr>
}
</table>


<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add new category</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" asp-area="admin" asp-controller="dash" asp-action="Addtocategory" enctype="multipart/form-data">
                    <label>Add category name:</label>
                    <input class="form-control border border-secondary rounded" type="text" id="category" asp-for="Name"><br><br>
                    <input type="checkbox" style="width:20px;height:20px;" asp-for="ischeck" value="true" /><br /><br />
                    <button type="submit" class="btn btn-primary">Add</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </form>
            </div>

        </div>
    </div>
</div>


<div class="modal fade" id="exampleModal3" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Change Category</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" asp-area="admin" asp-controller="dash" asp-action="Edit_category5" enctype="multipart/form-data">
                   <input asp-for="Id" type="text" id="categoryId" hidden><br>
                    <label  data-binding="Customer first name">Edit Category</label><br>
                    <input asp-for="Name" type="text" id="editCategoryName" class="form-control border border-secondary rounded"><br><br>
                    <input type="checkbox" style="width:20px;height:20px;" asp-for="ischeck" value="true" /><br /><br />
                    <button type="submit" class="btn btn-primary">Change category</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </form>


            </div>

        </div>
    </div>
</div>
<script>
    function updateCategory(checkbox) {
        var categoryId = checkbox.getAttribute('data-id');
        var isChecked = checkbox.checked;

        var xhr = new XMLHttpRequest();
        xhr.open('POST', '/admin/dash/UpdateCategory', true);
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.onreadystatechange = function () {
            if (xhr.readyState === XMLHttpRequest.DONE) {
                if (xhr.status === 200) {
                    console.log('Update successful' + categoryId + isChecked);
                } else {
                    console.error('Update failed:', xhr.status);
                }
            }
        };
        xhr.send(JSON.stringify({ id: categoryId,isChecked}));
    }
</script>
<script>
    function ajaxx(data,mata) {
       // alert('Value of luk: ' + data+ "  "+mata);
        document.getElementById('categoryId').value = data;
        document.getElementById('editCategoryName').value = mata;
    };
    function updateCategory(id, isChecked) {
        fetch('/Category/UpdateCategory', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'RequestVerificationToken': $('input[name="__RequestVerificationToken"]').val() // Include Anti-Forgery Token if needed
            },
            body: JSON.stringify({ id: id, isCheck: isChecked })
        })
            .then(response => response.ok ? console.log('Update successful') : console.error('Update failed'))
            .catch(error => console.error('Error:', error));
    }
   
</script>

PROJECT_Trading_Platform/Front-5/Areas/Admin/Views/Dash/Edit.cshtml
@model Sport_pro

<form method="post" asp-area="admin" asp-controller="dash" asp-action="Edit" enctype="multipart/form-data" class="custom-form">
    <label for="Text">Text:</label>
    <input type="text" id="Text" asp-for="name" class="input-field"><br>

    <label for="photo1">photo1</label>
    <input type="file" id="photo1" asp-for="file1" class="input-field-file"><br>

  
        <label for="photo2">photo2</label>
        <input type="file" id="photo2" asp-for="file2" class="input-field-file">

        <br>

    <label for="Images">Other pictures</label>
    <input type="file" id="Images" asp-for="Images" class="input-field-file" multiple="multiple"><br>

    <label for="price">Price</label>
    <input type="text" id="price" asp-for="price" class="input-field"><br>

    <select id="CategoryId" asp-for="CategoryId" class="select-field">

        @foreach (var item in ViewBag.Categories)
        {
            <option value="@item.Id">@item.Name</option>
        }
    </select>

    <select id="CategorytwoId" class="select-field" asp-for="CategorytwoId">
        @foreach (var item in ViewBag.Categories_two)
        {
            <option value="@item.Id">@item.Name</option>
        }
    </select>

    <select id="CategorytwoId" class="select-field" asp-for="ColorId">
        @foreach (var item in ViewBag.Colors)
        {
            <option value="@item.Id">@item.color</option>
        }
    </select>
    <select id="SizeId" class="select-field" asp-for="SizeId">
        @foreach (var item in ViewBag.Size)
        {
            <option value="@item.Id">@item.name</option>
        }
    </select>
    <input type="submit" class="submit-button">
</form>

<style>
    .custom-form {
        border: 2px solid #28a745; /* Green border */
        padding: 20px;
        width: 300px;
        margin-left : 50px;
    }

    .input-field {
        width: 100%;
        padding: 8px;
        margin-bottom: 10px;
        box-sizing: border-box; /* Make sure that padding and border are included in the width */
    }

    .input-field-file {
        margin-bottom: 10px;
    }

    .select-field {
        width: 100%;
        padding: 8px;
        margin-bottom: 10px;
        box-sizing: border-box; /* Make sure that padding and border are included in the width */
    }

    .submit-button {
        background-color: #28a745; /* Green */
        color: white;
        padding: 10px 20px;
        border: none;
        cursor: pointer;
        width: 100%;
    }

        .submit-button:hover {
            background-color: #218838; /* Darker green */
        }
</style>

PROJECT_Trading_Platform/Front-5/Areas/Admin/Views/Dash/Order_list.cshtml
@model List<Orders>;
<h3 style="margin:20px">Order list</h3>
<table>
    <thead>
        <tr>
            <th>Order</th>
            <th>Order Description</th>
            <th>Order Time</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.price</td>
                <td>@item.Date</td>
            </tr>
        }
    </tbody>
</table>
<style>
    table {
        width: 90%;
        border-collapse: collapse;
    }

    th, td {
        border: 1px solid #000; 
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }
</style>

PROJECT_Trading_Platform/Front-5/Areas/Admin/Views/Dash/Users_list.cshtml
@model List<User>;
@{
    var userRoles = ViewBag.UserRoles as Dictionary<string, string>;
}
<h3 style="margin:20px">User's</h3>


<table>
    <thead>
        <tr>
            <th>User Name</th>
            <th>User</th>
            <th>Delete this user</th>
            <th>Make this user Admin</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.UserName</td>
                <td>@userRoles[user.Id]</td>
                <th><a href="#" onclick="confirmDelete(@user.Age)" class="btn btn-danger">Delete this user</a></th>
                <th>
                    <form asp-action="PromoteToAdmin" asp-route-userId="@user.Id" method="post">
                        <button type="submit" class="btn btn-success">Make this user Admin</button>
                    </form>
                </th>
            </tr>
        }
    </tbody>
</table>
<script>
    function confirmDelete(itemAge) {
        Swal.fire({
            title: 'Are you sure?',
            text: 'Once deleted, you will not be able to recover this User!',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete this user!',
            cancelButtonText: 'No, cancel!',
            reverseButtons: true
        }).then((result) => {
            if (result.isConfirmed) {
                // If user confirms, redirect to the delete action URL
                window.location.href = '/Admin/dash/DeleteUserByAge?age=' + itemAge;
            } else {
                // If user cancels, do nothing
            }
        });
    }
</script>
<style>
    table {
        width: 90%;
        border-collapse: collapse;
    }

    th, td {
        border: 1px solid #000;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }
</style>


<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>